name: test

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/test-workflow.yml
    secrets:
      github_packages_token: ${{ secrets.PACKAGES_TOKEN }}
      turbo_token: ${{ secrets.TURBO_TOKEN }}
